# -*- coding: utf-8 -*-
"""pregunata5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jqlNBUQ8MGy1l91iQqQZ7KH9_dRpHmz
"""

from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

engine = create_engine('sqlite:///agent.db', echo=True)
Base = declarative_base()

class Item(Base):
    __tablename__ = 'items'

    id = Column(Integer, primary_key=True)
    name = Column(String)
    category = Column(String)
    price = Column(Integer)

Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

items_data = [
    {'name': 'Laptop', 'category': 'Electronics', 'price': 1000},
    {'name': 'Chair', 'category': 'Furniture', 'price': 200},
    {'name': 'Book', 'category': 'Books', 'price': 20},
    {'name': 'Tablet', 'category': 'Electronics', 'price': 500},
    {'name': 'Desk', 'category': 'Furniture', 'price': 300},
]

for item_data in items_data:
    item = Item(**item_data)
    session.add(item)

session.commit()

from sqlalchemy import and_

def search_products_below_price_limit(session, category, price_limit):
    products = session.query(Item).filter(and_(Item.category == category, Item.price < price_limit)).all()
    return products

results = search_products_below_price_limit(session, 'Electronics', 600)

print("Products Found:")
for product in results:
    print(f"Name: {product.name}, Category: {product.category}, Price: ${product.price}")